### ISSUE TITLE
Build .deb and .rpm's InfluxDB 2.0

### ISSUE THREAD

**Issue by russorat** [influxdata/build-scripts#1]
The same way we have this for 1.x, we will need a `influxdb-2.0.0.x86_64.rpm` binary.

**Comment by russorat** [comment]
We now need to build this for both the standard influx package as well as the influx_client package.

**Comment by mhall119** [comment]
These are buildable with what's in the build-scripts repository. @russorat can this issue be closed?

**Comment by russorat** [comment]
How do we ensure these get built as part of the release process? @mark-rushakoff ?

**Comment by mhall119** [comment]
I think @gshif has been tasked with integrating those scripts with the CI/CD pipeline

**Comment by gshif** [comment]
@russorat , @mhall119 I am not sure I am the right person to integrate the scripts. I think it should be someone who is already familiar with what needs to be done.

**Comment by mhall119** [comment]
We have the option to use the same company who built these scripts, if somebody is able to approve the budget for a new contract with them

**Comment by psteinbachs** [comment]
@gshif and I will sync on this and work out how to move it forward.

**Comment by russorat** [comment]
i think we do this now.
